url: 'https://cometsfor.org'
baseurl: '/'
title: 'Comets for Better Transit'

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
  - package-lock.json
